---
  # yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
  #
  # Version 1.0.0
  # Author: Michael Bragg <mike@vatu.co.uk>

name: 'Commit'

on:
  push:
    branches:
      - 'main'
      - 'trunk'

  pull_request:
    types:
      - opened
      - edited
      - synchronize

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}--${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:

  validate-dependabot:
    name: 'Validate Dependabot Config'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v4.1.1'
      - uses: 'marocchino/validate-dependabot@v2.2.0'
        id: validate
      - uses: 'marocchino/sticky-pull-request-comment@v2.9.0'
        if: always()
        with:
          header: validate-dependabot
          message: ${{ steps.validate.outputs.markdown }}

  validate-composer:
    name: 'Validate Composer config'
    runs-on: 'ubuntu-latest'

    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v4.1.1"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@2.29.0"
        with:
          php-version: "latest"
          coverage: "none"
          tools: composer

      - name: 'Validate Composer'
        run: |
          composer validate
