---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
#
# Version 1.0.1
# Author: Michael Bragg <mike@vatu.co.uk>

name: 'Commit'

permissions:
  pull-requests: write

on:
  push:
    branches:
      - 'main'
      - 'trunk'

  pull_request:
    types:
      - opened
      - edited
      - synchronize

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}--${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:

  validate-dependabot:
    name: 'Validate Dependabot Config'
    runs-on: 'ubuntu-24.04'
    steps:
      - uses: 'actions/checkout@v5.0.0'
      - uses: 'marocchino/validate-dependabot@v3.0.0'
        id: validate
      - uses: 'marocchino/sticky-pull-request-comment@v2.9.4'
        if: always()
        with:
          header: validate-dependabot
          message: ${{ steps.validate.outputs.markdown }}

  validate-composer:
    name: 'Validate Composer config'
    runs-on: 'ubuntu-24.04'

    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v5.0.0"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@2.35.3"
        with:
          php-version: "latest"
          coverage: "none"
          tools: composer

      - name: 'Validate Composer'
        run: |
          composer validate
