---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
#
# Version 1.0.0
# Author: Michael Bragg <mike@vatu.dev>

name: 'Commit'

permissions:
  pull-requests: write

on:
  push:
    branches:
      - 'trunk'

  pull_request:
    types:
      - opened
      - edited
      - synchronize

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}--{{github.ref_name }}
  cancel-in-progress: true

env:
  COMPOSER_ALLOW_SUPERUSER: "1" # https://getcomposer.org/doc/03-cli.md#composer-allow-superuser

jobs:

  lint:
    name: "Lint"
    runs-on: "ubuntu-24.04"

    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        php-version: ['8.1']

    steps:

      - name: "Check out the repository."
        uses: "actions/checkout@v4.2.2"

      - name: "Set up PHP environment."
        uses: "shivammathur/setup-php@2.35.3"
        with:
          coverage: "none"
          ini-values: "memory_limit=-1"
          tools: "composer"
          ini-file: none
          php-version: "${{ matrix.php-version }}"
        env:
          COMPOSER_TOKEN: ${{ secrets.github-token }}

      - name: "Get Composer Cache Directory."
        run: |
          composer validate --ansi --strict

  security:
    name: "Security Analysis"
    runs-on: "ubuntu-24.04"

    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        php-version: ['8.1']

    steps:

      - name: "Check out the repository."
        uses: "actions/checkout@v4.2.2"

      - name: "Set up PHP environment."
        uses: "shivammathur/setup-php@2.35.3"
        with:
          coverage: "none"
          ini-values: "memory_limit=-1"
          tools: "composer"
          ini-file: none
          php-version: "${{ matrix.php-version }}"
        env:
          COMPOSER_TOKEN: ${{ secrets.github-token }}

      - name: "Get Composer Cache Directory."
        id: "composer-cache"
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: "Sets up Caching."
        uses: "actions/cache@v4.2.1"
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-php-composer-build-${{ hashFiles('composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-${{ matrix.php-version }}-composer-build-

      - name: "Install dependencies."
        run: |
          composer install --no-interaction --prefer-dist --no-dev  --ignore-platform-reqs

      - name: "Logs debug information."
        run: |
          php --version
          composer --version

      - name: "Run security test."
        run: |
          composer audit --ansi

  install:
    name: "Install dependencies"
    runs-on: "ubuntu-24.04"
    needs:
     - lint
     - security

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "7.4"
          - "8.0"
          - "8.1"
          - "8.2"
          - "8.3"
          - "8.4"

        dependencies:
          - "lowest"
          - "highest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4.2.2"

      - name: "Set up PHP"
        uses: "shivammathur/setup-php@2.35.3"
        with:
          coverage: "none"
          ini-values: "memory_limit=-1"
          tools: "composer"
          ini-file: none
          php-version: "${{ matrix.php-version }}"

      - name: "Logs debug information."
        run: |
          php --version
          composer --version

      - name: "Validate composer.json and composer.lock"
        run: "composer validate --ansi --strict"

      - name: "Install ${{ matrix.dependencies }} dependencies with composer"
        if: ${{ matrix.dependencies == 'lowest' }}
        run: |
          composer update --ansi --no-interaction --no-progress --prefer-lowest --working-dir="${GITHUB_WORKSPACE}"

      - name: "Install ${{ matrix.dependencies }} dependencies with composer"
        if: ${{ matrix.dependencies == 'highest' }}
        run: |
          composer install --ansi --no-interaction --no-progress --working-dir="${GITHUB_WORKSPACE}"
