# Vatu:   Dependabot Auto Merge
# Author: Michael Bragg <mike@vatu.co.uk>
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: "Dependabot Validate"

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/dependabot.yml'
      - '.github/workflows/dependabot-validate.yml'
jobs:
  validate:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: marocchino/validate-dependabot@v2
        id: validate
#       - uses: marocchino/sticky-pull-request-comment@v2
#         if: always()
#         with:
#           header: validate-dependabot
#           message: ${{ steps.validate.outputs.markdown }}
